server:
  port: 8080

spring:
  application:
    name: customer
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: 'imodupsy'
    password: 'password'
    driver-class-name: org.postgresql.Driver